### ISSUE TITLE
your blog page footer/sidebar has broken "On Delicous" and "Google+"

### ISSUE THREAD

**Issue by skierpage** [pnkfelix/pnkfx-blog#4]
This Week in Rust linked to http://blog.pnkfx.org/blog/2021/04/26/road-to-turbowish-part-1-goals/ . On a Pixel 3 in both Firefox for Android and Chrome, the bottom of the page has charmingly retro links [My Delicious Bookmarks »](http://delicious.com/pnkfelix) and [Google+](https://plus.google.com/pnkfelix?rel=author):
![Screenshot of The {pnk}f(eli)x Blog](https://user-images.githubusercontent.com/1303668/116655687-5d1b3f80-a940-11eb-99e2-485f75718fb7.png)
Delightfully old-skool but neither goes anywhere useful. In a wider browser window these appear to the right. The HTML for them is in source/_includes/asides/{delicious,googleplus}.html.

No worries, I've got non-functional Blogger "Links to this post" all over my old blog :wink: . And your footnotes that become asides is great responsive design, respect.

**Comment by pnkfelix** [comment]
Thanks for filing this.sorry I've overlooked it for nearly a year (!)

I'll see what I can do to resolve it. I'm tempted to just disable the delicious and g+ integration entirely. It will cause some conversations to be lost, but my memory is that that won't be any big loss.

**Comment by pnkfelix** [comment]
(oh, I was thinking of disqus. delicious is clearly dead, thanks!)
